Add Depth Buffer and Other Goodies
cohaereo/alkahest pull request #17
Opened 2024-01-20 08:38 UTC by Froggy618157725

This adds the ability to query the depth buffer, and uses it to improve Utility object placement.
To assist with look based placement, this also adds an optional crosshair. It's not very good...

2024-01-21 13:44 UTC, cohaereo requested changes

2024-01-22 11:37 UTC, Froggy618157725 commented on assets/shaders/crosshair.hlsl
Adjusted so it should look better in most circumstances.

2024-01-24 05:33 UTC, Froggy618157725 commented on src/overlays/menu.rs
> +                                        camera.position
I think I'll leave the ruler as it was before in that case, otherwise people might wonder what's at whatever nonzero distance it is.

2024-01-24 09:05 UTC, cohaereo approved these changes

2024-01-24 09:06 UTC, merged